# Generated by Django 5.1.1 on 2024-11-12 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saude', '0006_remove_locais_doencas_doenca_locais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locais_doencas',
            name='doenca_bairro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='saude.doencasbairro'),
        ),
    ]
